### ISSUE TITLE
Working towards 1.0.0

### ISSUE THREAD

**Issue by antoniomika** [antoniomika/sish#85]
Seeing as I have a bit more time on my hands, I think there are a few changes I'd like to make to sish, mainly revolving around ease of use and updating paradigms. Here are the things I am looking to do:

- [x] Change the documentation of CLI flags to be more explicit and describe the action they represent better. This stems from #80 and #81 
    - [x] Remove the `sish.` prefix on commands.
    - [x] My current plan is to switch to using [Cobra](https://github.com/spf13/cobra) and [Viper](https://github.com/spf13/viper) [together](https://github.com/spf13/cobra#bind-flags-with-config). Both of which are great tools that are used in numerous other projects.
    - [x] I'm gonna try to focus on inline documentation also. I wrote sish in a few hours on a whim, it seems like some people are really getting good use out of it so I think it's time to focus on it more.
- [x] Update documentation of how to deploy with LetsEncrypt. The container I used for this previously has changed *drastically*. This stems from #82.
- [x] Update the admin console to use a data-binding tool. This stems from #84 
    - [x] I think knockout.js was mentioned and I'm fine with that. We might want to consider vendoring the assets we currently use, but I'm also fine with leaving it as is.
- [x] Add aarch64 builds

**Comment by antoniomika** [comment]
#86 has been merged!
